### ISSUE TITLE
Enhance helper text for string lint command

### ISSUE THREAD

**Issue by kudalies** [g-Off/stringray#5]
Right now, `stringray lint` or `stringray lint <filepath>` does not work.
`stringray lint -h` only says it has 1 option of `--list, -l List available rules and default configuration`

Add helper text to indicate usage of `stringray lint` can include option `stringray lint --input` and what `--input, -i` means.

**Comment by g-Off** [comment]
`stringray lint <path>` would also be nice, but I'm not sure how to do this with the command line option parsing so that `-h` or `-l` are also possible for spitting out the list of lint rules
